config/routes.rb
CptCup::Application.routes.draw do
  resources :players

  resources :leagues do
    resources :games do
      get :odds, :on => :collection
      get :shot_tracker, :on => :member
      post :create_shot, :on => :member
      post :select_winner, :on => :member
    end
  end

  namespace :admin do
    resources :leagues, except: :show
    resources :games, except: :show
  end

  get '/admin' => "admin/leagues#index"
  root :to => "leagues#index"
end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :name
  validates_presence_of :name, :start_date

  default_scope order: 'start_date DESC'

  has_many :games, order: "created_at ASC", dependent: :restrict

  before_destroy :validate_not_completed

  private

  def validate_not_completed
    unless end_date.nil?
      self.errors.add(:base, "cant delete a league that's completed")
      return false
    end
  end
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < ApplicationController
  before_filter :authenticate
  layout 'admin'

  # GET /admin/leagues
  # GET /admin/leagues.json
  def index
    @leagues = League.reorder("id ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /admin/leagues/new
  # GET /admin/leagues/new.json
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /admin/leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /admin/leagues
  # POST /admin/leagues.json
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to admin_leagues_path, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/leagues/1
  # PUT /admin/leagues/1.json
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to admin_leagues_path, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/leagues/1
  # DELETE /admin/leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to admin_leagues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :set_league, :calculate_data, :only => [:show]

  def index
    @leagues = League.all
    @player = Player.new
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @game = @league.games.build
    @game.build_default_assocations
    @num_games = @league.games.count

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  private

  def set_league
    @league = League.find(params[:id])
  end

  def calculate_data
    #refactor this into models, theres prolly a better way to structure this...
    game_hash = {}
    Player.all.each {|player| game_hash[player.id] = PlayerComparison.new }

    @league.games.each do |g|
      next if g.is_team_one_victory.nil?

      # WINS / LOSSES
      if g.is_team_one_victory
        winner_one_id = g.player_one.id
        winner_two_id = g.player_two.id
        loser_one_id = g.player_three.id
        loser_two_id = g.player_four.id
      else
        winner_one_id = g.player_three.id
        winner_two_id = g.player_four.id
        loser_one_id = g.player_one.id
        loser_two_id = g.player_two.id
      end

      game_hash[winner_one_id].add_wins_against(loser_one_id, loser_two_id, g.cups_left)
      game_hash[winner_two_id].add_wins_against(loser_one_id, loser_two_id, g.cups_left)
      game_hash[loser_one_id].add_loses_against(winner_one_id, winner_two_id, g.cups_left)
      game_hash[loser_two_id].add_loses_against(winner_one_id, winner_two_id, g.cups_left)

      # SHOTS HITS / MISSES
      g.shots.each do |shot|
        shooter_id = shot.player_id

        if [g.player_one.id, g.player_two.id].include?(shooter_id)
          opponent_1_id, opponent_2_id = g.player_three.id, g.player_four.id
        elsif [g.player_three.id, g.player_four.id].include?(shooter_id)
          opponent_1_id, opponent_2_id = g.player_one.id, g.player_two.id
        end

        game_hash[shooter_id].add_shot(shot, opponent_1_id, opponent_2_id)
      end
    end

    @game_hash = {}
    game_hash.to_a.each {|arr| @game_hash[arr.first] = arr.last.against_hash.to_a}

    #refactor this to a call to the League for players
    @players_hash = Player.all.inject({}) do |hash, p|
      hash[p.id] = p.name; hash
    end.select {|player_id| @game_hash[player_id].present?}

    @game_hash.reject! {|player_id, games_arr| games_arr.empty? }

    #refactor this, move it to League, doesnt need any params...
    @player_rankings = Game.calculate_rankings(@league.games)
  end
end

app/views/leagues/_comparisons.html.erb
<% content_for :head do %>
<style>
  body {
    font-family: Baskerville, "Times New Roman", serif;
  }
  #svg-container {
    margin-top: 2em;
  }
  .bar:hover,
  .player-names:hover {
    cursor: pointer;
  }
</style>
<% end %>

<div class="controls">
  <label> Player:
    <select id="player-selector">
      <option value="all">--</option>
      <% @players_hash.sort_by { |id, name| name.downcase }.each do |k,v| %>
      <option value="<%= k %>"><%= v %></option>
      <% end %>
    </select>
  </label>
  <label> Sort By:
    <select id="sort-type">
      <option value="ranking">Ranking</option>
      <option value="plusminus">Plus/Minus</option>
      <option value="games">Most Games</option>
      <option value="wins">Most Wins</option>
      <option value="losses">Most Losses</option>
      <option value="winLoss">Win/Loss Ratio</option>
      <option value="domination">Domination</option>
      <option value="pwned">Pwned</option>
      <option value="cups-left">Margin Of Victory (Total Cups)</option>
      <option value="cups-left-average">Margin Of Victory (Average Cups/Game)</option>
      <option value="shots">Shot Percentage</option>
      <option value="three-rack-shots">Clutchness (Shot Percentage On 3-Racks)</option>
    </select>
  </label>
</div>

<svg id="svg-container"></svg>

<% content_for :script do %>
<%= javascript_include_tag('d3/d3.js') %>
<script>
  var VsPlayer = function(id, wins, losses, shotsHit, shotsMissed, threeRackShotsHit, threeRackShotsMissed, cupsLeft) {
    this.id = id;
    this.wins = wins;
    this.losses = losses;
    this.totalGames = this.wins + this.losses
    this.plusMinus = this.wins - this.losses;
    this.winRatio = this.wins / this.totalGames;

    this.cupsLeft = cupsLeft;
    this.cupsLeftRatio = this.cupsLeft / this.totalGames;

    this.shotsHit = shotsHit;
    this.shotsMissed = shotsMissed;
    this.totalShots = this.shotsHit + this.shotsMissed;
    if (this.totalShots == 0) {
      this.shotPercentage = 0;
    } else {
      this.shotPercentage = this.shotsHit / this.totalShots;
    }

    this.threeRackShotsHit = threeRackShotsHit;
    this.threeRackShotsMissed = threeRackShotsMissed;
    this.totalThreeRackShots = this.threeRackShotsHit + this.threeRackShotsMissed;
    if (this.totalThreeRackShots == 0) {
      this.threeRackShotPercentage = 0;
    } else {
      this.threeRackShotPercentage = this.threeRackShotsHit / this.totalThreeRackShots;
    }
  }
  var Player = function(id, records) {
    this.id = id;
    this.records = records;
    this.versusArray = [];
    this.wins = 0;
    this.losses = 0;
    this.cupsLeft = 0;
    this.shotsHit = 0;
    this.shotsMissed = 0;
    this.threeRackShotsHit = 0;
    this.threeRackShotsMissed = 0;
    this.score = 1200;
    var self = this;
    this.numGames = function() {
      return self.versusArray.length;
    }
    this.setRankingScore = function(s) {
      this.score = s;
    }
    var addVersus = function(vsPlayer) {
      self.versusArray.push(vsPlayer);
    }
    var initializeVersus = function() {
      $.each(self.records, function(i, idWinLossArr) {
        var vs = new VsPlayer(idWinLossArr[0], idWinLossArr[1][0], idWinLossArr[1][1], idWinLossArr[1][2], idWinLossArr[1][3], idWinLossArr[1][4], idWinLossArr[1][5], idWinLossArr[1][6]);
        addVersus(vs);
        self.wins += vs.wins;
        self.losses += vs.losses;
        self.cupsLeft += vs.cupsLeft;
        self.shotsHit += vs.shotsHit;
        self.shotsMissed += vs.shotsMissed;
        self.threeRackShotsHit += vs.threeRackShotsHit;
        self.threeRackShotsMissed += vs.threeRackShotsMissed;
      });
    }
    initializeVersus();
    // each game has 2 opponents
    this.wins /= 2;
    this.losses /= 2;
    this.totalGames = this.wins + this.losses;
    this.plusMinus = this.wins - this.losses;
    this.winRatio = this.wins / this.totalGames;

    this.cupsLeft /= 2;
    this.cupsLeftRatio = this.cupsLeft / this.totalGames;

    this.shotsHit /= 2;
    this.shotsMissed /= 2;
    this.totalShots = this.shotsHit + this.shotsMissed;
    if (this.totalShots == 0) {
      this.shotPercentage = 0;
    } else {
      this.shotPercentage = this.shotsHit / this.totalShots;
    }

    this.threeRackShotsHit /= 2;
    this.threeRackShotsMissed /= 2;
    this.totalThreeRackShots = this.threeRackShotsHit + this.threeRackShotsMissed;
    if (this.totalThreeRackShots == 0) {
      this.threeRackShotPercentage = 0;
    } else {
      this.threeRackShotPercentage = this.threeRackShotsHit / this.totalThreeRackShots;
    }

   console.log(this.threeRackShotsHit, this.threeRackShotsMissed, this.totalThreeRackShots, this.threeRackShotPercentage);

  }
  var chart = {
    w: 500,
    h: 1200,
    nameGap: 100,
    unitWidth: 20,
    barStart: function() { return this.nameGap },
    em: function(units) { return units * 13; }
  }
  var rankings = <%= @player_rankings.to_json.html_safe %>;
  var namesHash = <%= @players_hash.to_json.html_safe %>;
  var data = <%= @game_hash.to_json.html_safe %>;
  var dataRecords = {};
  $.each(data, function(k, v) {
    dataRecords[k] = new Player(k, v);
  });
  $.each(rankings, function(k, v) {
    dataRecords[k].setRankingScore(v);
  });

  var x = d3.scale.linear()
    .domain([0, 1])
    .range([0, chart.w]);
  var y = d3.scale.linear()
    .domain([0, 100])
    .rangeRound([0, chart.h]);

  var svg = d3.select('svg')
    .attr('width', chart.w)
    .attr('height', chart.h);

  $("#player-selector").change(function() {
    var id = $(this).find(":selected").val();
    var type = $("#sort-type").val();
    if (id != "all" && type == "ranking") {
      $("#sort-type").val("plusminus");
      type = "plusminus";
    }
    drawComparisons($(this).find(":selected").val(), $('#sort-type').val());
  }).val("all");

  $("#sort-type").change(function() {
    var id = $("#player-selector").find(":selected").val();
    var type = $(this).val();
    if (type == "ranking") {
      $("#player-selector").val('all');
      id = "all"
    }
    drawComparisons(id, type);
  });

  function getPlayerData(playerId) {
    if (isNaN(playerId)) {
      return $.map(dataRecords, function (value, key) { return value; });;
    } else {
      return dataRecords[playerId].versusArray;
    }
  }

  function drawComparisons(playerId, sortType) {
    var dataPoints = transformData(getPlayerData(playerId), sortType);
    drawBars(dataPoints, sortType);
    drawNamesLabel(dataPoints);
    drawBarLabel(dataPoints, sortType);
    drawAgainstLabel(dataPoints, sortType);
  }

  function transformData(data, sortType) {
    var data = data.sort(function(p1, p2) {
      switch(sortType) {
        case "ranking":
          return d3.descending(p1.score, p2.score);
        case "plusminus":
          return d3.descending(p1.plusMinus, p2.plusMinus);
        case "games":
          return d3.descending(p1.totalGames, p2.totalGames);
        case "wins":
          return d3.descending(p1.wins, p2.wins);
        case "losses":
          return d3.descending(p1.losses, p2.losses);
        case "cups-left":
          return d3.descending(p1.cupsLeft, p2.cupsLeft);
        case "cups-left-average":
          return d3.descending(p1.cupsLeftRatio, p2.cupsLeftRatio);
        case "winLoss":
        case "domination":
          if (p1.winRatio == p2.winRatio) {
            if (p1.plusMinus == p2.plusMinus) {
              return d3.descending(p1.wins, p2.wins);
            } else {
              return d3.descending(p1.plusMinus, p2.plusMinus);
            }
          } else {
            return d3.descending(p1.winRatio, p2.winRatio);
          }
        case "pwned":
        if (p1.winRatio == p2.winRatio) {
          if (p1.plusMinus == p2.plusMinus) {
            return d3.descending(p2.wins, p1.wins);
          } else {
            return d3.descending(p2.plusMinus, p1.plusMinus);
          }
        } else {
          return d3.descending(p2.winRatio, p1.winRatio);
        }
        case "shots":
          return d3.descending(p1.shotPercentage, p2.shotPercentage);
        case "three-rack-shots":
          return d3.descending(p1.threeRackShotPercentage, p2.threeRackShotPercentage);
      }
    });

    if (sortType == "domination") {
      data = data.filter(function(vsPlayer) {
        return vsPlayer.winRatio >= 0.75 && vsPlayer.totalGames >= 2;
      });
    } else if (sortType == "pwned") {
      data = data.filter(function(vsPlayer) {
        return vsPlayer.winRatio <= 0.25 && vsPlayer.totalGames >= 2;
      });
    }

    return data;
  }

  function drawBars(data, sortType) {
    var bars = svg.selectAll('rect')
      .data(data)
      .on('click', function(d) { $('#player-selector').val(d.id).change(); });
    bars.enter().append('rect');
    bars.transition().duration(1000)
      .attr('class', "bar")
      .attr('x', function(d) { return chart.barStart(); })
      .attr('fill', function(d) {
        switch(sortType) {
          case "plusminus":
            if (d.plusMinus > 0) {
              return "rgb(0, " + (Math.abs(d.plusMinus) * 50) + ", 0)";
            } else {
              return "rgb(" + (Math.abs(d.plusMinus) * 50) + ", 0, 0)";
            }
          case "cups-left":
            if (d.cupsLeft > 0) {
              return "rgb(0, " + (Math.abs(d.cupsLeft) * 5) + ", 0)";
            } else {
              return "rgb(" + (Math.abs(d.cupsLeft) * 5) + ", 0, 0)";
            }
          case "cups-left-average":
            if (d.cupsLeftRatio > 0) {
              return "rgb(0, " + (Math.abs(d.cupsLeftRatio) * 50) + ", 0)";
            } else {
              return "rgb(" + (Math.abs(d.cupsLeftRatio) * 50) + ", 0, 0)";
            }
          case "ranking":
          case "winLoss":
          case "games":
          case "domination":
          case "pwned":
            return "#000";
          case "wins":
          case "losses":
            if (barWidth(d, sortType) > 1 && sortType != "losses") {
              return "rgb(0, " + (barWidth(d, sortType) * 20) + ", 0)";
            } else {
              return "rgb(" + (barWidth(d, sortType) * 20) + ", 0, 0)";
            }
        }
      })
      .attr('y', function(d, i) { return i * chart.unitWidth; })
      .attr('width', function(d) { return barWidth(d, sortType) * chart.em(2); })
      .attr('height', 15);
    bars.exit().remove();
  }

  function drawNamesLabel(data) {
    var label = svg.selectAll('.player-names')
      .data(data)
      .on('click', function(d) { $('#player-selector').val(d.id).change(); });
    label.enter().append("text");
    label.transition().duration(1000)
      .attr('class', "player-names")
      .attr('x', function(d) { return chart.barStart() - chart.em(1); })
      .attr('y', textYCoord)
      .attr("text-anchor", "end")
      .text(function(d) { return namesHash[d.id]; });
    label.exit().remove();
  }

  function drawBarLabel(data, sortType) {
    var label = svg.selectAll('.plus-minus')
      .data(data)
    label.enter().append("text");
    label.transition().duration(1000)
      .attr('class', 'plus-minus')
      .attr('x', function(d) { return chart.barStart() + 5; })
      .attr('fill', function(d) { return sortType == "ranking" ? "#000" : "#fff"; })
      .attr('y', textYCoord)
      .text(function(d) {
        switch(sortType) {
          case "ranking":
            return d.score.toFixed(2);
          case "plusminus":
            return (d.plusMinus > 0 ? "+" : "") + d.plusMinus;
          case "cups-left":
            return (d.cupsLeft > 0 ? "+" : "") + d.cupsLeft;
          case "cups-left-average":
            return (d.cupsLeftRatio > 0 ? "+" : "") + d.cupsLeftRatio;
          case "games":
            return d.totalGames;
          case "winLoss":
          case "domination":
          case "pwned":
            return d.winRatio.toFixed(3);
          case "wins":
            return d.wins;
          case "losses":
            return d.losses;
          case "shots":
            return d.shotPercentage.toFixed(3);
          case "three-rack-shots":
            return d.threeRackShotPercentage.toFixed(3);
        }
      });
    label.exit().remove();
  }

  function drawAgainstLabel(data, sortType) {
    var label = svg.selectAll('.against-label')
      .data(data)
    label.enter().append("text");
    label.transition().duration(1000)
      .attr('class', 'against-label')
      .attr('x', function(d) { return chart.barStart() + barWidth(d, sortType) * chart.em(2) + 5; })
      .attr('y', textYCoord)
      .text(function(d) {
        switch(sortType) {
          case "ranking":
            return "";
          default:
            return "W-L " + d.wins + "-" + d.losses;
        }
      });
    label.exit().remove();
  }

  function barWidth(player, sortType) {
    switch(sortType) {
      case "ranking":
        return 0;
      case "plusminus":
        return Math.max(player.plusMinus, 0) + 1;
      case "cups-left":
        return Math.max(player.cupsLeft, 0) + 1;
      case "cups-left-average":
        return Math.max(player.cupsLeftRatio, 0) + 1;
      case "games":
        return player.totalGames / 10;
      case "wins":
        return player.wins / 10 ;
      case "losses":
        return player.losses / 10;
      case "winLoss":
        return (player.winRatio * 10) + 1;
      case "shots":
        return (player.shotPercentage * 10) + 1;
      case "three-rack-shots":
        return (player.threeRackShotPercentage * 10) + 1;
      case "domination":
      case "pwned":
    }   return 5;
  }

  function textYCoord(d, i) {
    return (i * chart.unitWidth) + chart.em(1);
  }

  drawComparisons('all', "ranking");
</script>
<% end %>

app/views/leagues/index.html.erb
<% content_for :head do %>
<style>
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  ul li {
    position: relative;
  }
  #leader-board {
    position: absolute;
    left: 300px;
    top: 4em;
  }
  .experimental {
    position: relative;
    float:right;
    padding-right: 1em;
  }
  .experimental sup {
    color: red;
    font-weight: bold;
    -moz-transform: rotate(-27deg);
    -webkit-transform: rotate(-27deg);
    display: block;
    left: -1em;
    position: absolute;
    top: -0.7em;
    font-size: 0.538em;
  }
</style>
<% end %>

<h1>Canuto Tacderan Cup</h1>

<h4>Select A League</h4>
<ul>
<% @leagues.each do |league| %>
<li><%= link_to league.name, league_path(league) %> (started on <%= league.start_date.strftime("%Y-%m-%d") %> | <%= pluralize(league.games.count, "game") %> played )</li>
<% end %>
</ul>

<h4>Create an Athlete</h4>
<%= render 'players/form' %>

<a href="<%= players_path %>">List all athletes</a>

app/views/leagues/show.html.erb
<% content_for :head do %>
<style>
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  ul li {
    position: relative;
  }
  #leader-board {
    position: absolute;
    left: 300px;
    top: 4em;
  }
  .experimental {
    position: relative;
    float:right;
    padding-right: 1em;
  }
  .experimental sup {
    color: red;
    font-weight: bold;
    -moz-transform: rotate(-27deg);
    -webkit-transform: rotate(-27deg);
    display: block;
    left: -1em;
    position: absolute;
    top: -0.7em;
    font-size: 0.538em;
  }
</style>
<% end %>

<div class="experimental">
  <ul>
    <li>
      <sup>New</sup>
      <a href="<%= odds_league_games_path(@league) %>">Odds Calculator</a>
  </ul>
</div>

<h1><%= @league.name %></h1>

<h4>Record a Game</h4>
<%= render 'games/form' %>

<h4>View Games</h4>
<p>Total Number of Games Recorded: <%= @num_games %></p>

<a href="<%= league_games_path(@league) %>">List all games</a>

<div id="leader-board">
  <h4>Leaderboard</h4>
  <%= render partial: 'comparisons' %>
</div>