config/routes.rb
CptCup::Application.routes.draw do
  resources :players

  resources :leagues do
    resources :games do
      get :odds, :on => :collection
      get :shot_tracker, :on => :member
      post :create_shot, :on => :member
      post :select_winner, :on => :member
    end
  end

  namespace :admin do
    resources :leagues, except: :show
    resources :games, except: :show
  end

  get '/admin' => "admin/leagues#index"
  root :to => "leagues#index"
end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :name
  validates_presence_of :name, :start_date

  default_scope order: 'start_date DESC'

  has_many :games, order: "created_at ASC", dependent: :restrict

  before_destroy :validate_not_completed

  private

  def validate_not_completed
    unless end_date.nil?
      self.errors.add(:base, "cant delete a league that's completed")
      return false
    end
  end
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < ApplicationController
  before_filter :authenticate
  layout 'admin'

  # GET /admin/leagues
  # GET /admin/leagues.json
  def index
    @leagues = League.reorder("id ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /admin/leagues/new
  # GET /admin/leagues/new.json
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /admin/leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /admin/leagues
  # POST /admin/leagues.json
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to admin_leagues_path, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/leagues/1
  # PUT /admin/leagues/1.json
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to admin_leagues_path, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/leagues/1
  # DELETE /admin/leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to admin_leagues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :set_league, :calculate_data, :only => [:show]

  def index
    @leagues = League.all
    @player = Player.new
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @game = @league.games.build
    @game.build_default_assocations
    @num_games = @league.games.count

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  private

  def set_league
    @league = League.find(params[:id])
  end

  def calculate_data
    #refactor this into models, theres prolly a better way to structure this...
    game_hash = {}
    Player.all.each {|player| game_hash[player.id] = PlayerComparison.new }

    @league.games.each do |g|
      next if g.is_team_one_victory.nil?

      # WINS / LOSSES
      if g.is_team_one_victory
        winner_one_id = g.player_one.id
        winner_two_id = g.player_two.id
        loser_one_id = g.player_three.id
        loser_two_id = g.player_four.id
      else
        winner_one_id = g.player_three.id
        winner_two_id = g.player_four.id
        loser_one_id = g.player_one.id
        loser_two_id = g.player_two.id
      end

      game_hash[winner_one_id].add_wins_against(loser_one_id, loser_two_id, g.cups_left)
      game_hash[winner_two_id].add_wins_against(loser_one_id, loser_two_id, g.cups_left)
      game_hash[loser_one_id].add_loses_against(winner_one_id, winner_two_id, g.cups_left)
      game_hash[loser_two_id].add_loses_against(winner_one_id, winner_two_id, g.cups_left)

      # SHOTS HITS / MISSES
      g.shots.each do |shot|
        shooter_id = shot.player_id

        if [g.player_one.id, g.player_two.id].include?(shooter_id)
          opponent_1_id, opponent_2_id = g.player_three.id, g.player_four.id
        elsif [g.player_three.id, g.player_four.id].include?(shooter_id)
          opponent_1_id, opponent_2_id = g.player_one.id, g.player_two.id
        end

        game_hash[shooter_id].add_shot(shot, opponent_1_id, opponent_2_id)
      end
    end

    @game_hash = {}
    game_hash.to_a.each {|arr| @game_hash[arr.first] = arr.last.against_hash.to_a}

    #refactor this to a call to the League for players
    @players_hash = Player.all.inject({}) do |hash, p|
      hash[p.id] = p.name; hash
    end.select {|player_id| @game_hash[player_id].present?}

    @game_hash.reject! {|player_id, games_arr| games_arr.empty? }

    #refactor this, move it to League, doesnt need any params...
    @player_rankings = Game.calculate_rankings(@league.games)
  end
end

app/views/admin/leagues/_form.html.erb
<%= form_for [:admin, @league]  do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_leagues_path %>

app/views/admin/leagues/index.html.erb
<h1>Listing Leagues</h1>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>id</th>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th></th>
    <th></th>
  </tr>

<% @leagues.each do |league| %>
  <tr>
    <td><%= league.id %></td>
    <td><%= league.name %></td>
    <td><%= league.start_date.to_formatted_s if league.start_date %></td>
    <td><%= league.end_date.to_formatted_s if league.end_date %></td>
    <td><%= link_to 'Edit', edit_admin_league_path(league) %></td>
    <td><%= link_to 'Destroy', [:admin, league], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New League', new_admin_league_path %>

app/views/admin/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_leagues_path %>