config/routes.rb
CptCup::Application.routes.draw do
  resources :players

  resources :leagues do
    resources :games do
      get :odds, :on => :collection
      get :shot_tracker, :on => :member
      post :create_shot, :on => :member
      post :select_winner, :on => :member
    end
  end

  namespace :admin do
    resources :leagues, except: :show
    resources :games, except: :show
  end

  get '/admin' => "admin/leagues#index"
  root :to => "leagues#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player_one, class_name: "Player", foreign_key: "player_one_id"
  belongs_to :player_two, class_name: "Player", foreign_key: "player_two_id"
  belongs_to :player_three, class_name: "Player", foreign_key: "player_three_id"
  belongs_to :player_four, class_name: "Player", foreign_key: "player_four_id"
  belongs_to :league
  has_many :shots, order: "created_at ASC"

  attr_accessible :cups_left,
    :player_one_id, :player_two_id, :player_three_id, :player_four_id, :league_id,
    :player_one, :player_two, :player_three, :player_four, :league, :is_team_one_victory

  attr_reader :team_1_score, :team_2_score

  validates_presence_of :player_one_id, :player_two_id, :player_three_id, :player_four_id, :league_id
  validate :not_same_player

  ELO_STARTING_SCORE = 1200
  ELO_K_FACTOR = 16
  ELO_MULTIPLIER = 400.0

  def expected_outcome(starting_score = ELO_STARTING_SCORE, k_factor = ELO_K_FACTOR, multiplier = ELO_MULTIPLIER)
    return false unless player_one && player_two && player_three && player_four

    players_score = Game.calculate_rankings(league.games, starting_score, k_factor, multiplier)

    @team_1_score = players_score[player_one.id] + players_score[player_two.id]
    @team_2_score = players_score[player_three.id] + players_score[player_four.id]

    team_1_expected = 1 / ( 1 + 10 ** ((team_2_score - team_1_score)/multiplier))
    team_2_expected = 1 / ( 1 + 10 ** ((team_1_score - team_2_score)/multiplier))

    return team_1_expected, team_2_expected
  end

  def total_winner_score(starting_score = ELO_STARTING_SCORE, k_factor = ELO_K_FACTOR, multiplier = ELO_MULTIPLIER)
    unless @team_1_score
      players_score = Game.calculate_rankings(league.games, starting_score, k_factor, multiplier)

      @team_1_score = players_score[player_one.id] + players_score[player_two.id]
    end

    @team_1_score
  end

  def total_loser_score(starting_score = ELO_STARTING_SCORE, k_factor = ELO_K_FACTOR, multiplier = ELO_MULTIPLIER)
    unless@team_2_score
      players_score = Game.calculate_rankings(league.games, starting_score, k_factor, multiplier)

      @team_2_score = players_score[player_three.id] + players_score[player_four.id]
    end

    @team_2_score
  end

  def self.calculate_rankings(games, starting_score = ELO_STARTING_SCORE, k_factor = ELO_K_FACTOR, multiplier = ELO_MULTIPLIER)
    players_score = Hash.new {|h, k| h[k] = starting_score}

    games.each do |g|
      next if g.is_team_one_victory.nil? #ignore incomplete games

      if g.is_team_one_victory
        winner_one_id = g.player_one.id
        winner_two_id = g.player_two.id
        loser_one_id = g.player_three.id
        loser_two_id = g.player_four.id
      else
        winner_one_id = g.player_three.id
        winner_two_id = g.player_four.id
        loser_one_id = g.player_one.id
        loser_two_id = g.player_two.id
      end

      winning_team_score = players_score[winner_one_id] + players_score[winner_two_id]
      losing_team_score = players_score[loser_one_id] + players_score[loser_two_id]

      winner_points = k_factor*(1-1/(1.0+10**((losing_team_score-winning_team_score)/multiplier)))

      players_score[winner_one_id] += winner_points
      players_score[winner_two_id] += winner_points
      players_score[loser_one_id] -= winner_points
      players_score[loser_two_id] -= winner_points
    end

    players_score
  end

  def team_1_hit_cups
    @team_1_hit_cups ||= self.shots.where(player_id: [player_one_id, player_two_id], is_hit: true).map(&:cup_position)
  end

  def team_2_hit_cups
    @team_2_hit_cups ||= self.shots.where(player_id: [player_three_id, player_four_id], is_hit: true).map(&:cup_position)
  end

  def build_default_assocations
    self.build_player_one unless self.player_one
    self.build_player_two unless self.player_two
    self.build_player_three unless self.player_three
    self.build_player_four unless self.player_four
  end

  def cup_is_hit?(team, cup_position)
    hit_cups = team == 1 ? team_1_hit_cups : team_2_hit_cups
    hit_cups.include?(cup_position)
  end

  def is_pending?
    self.is_team_one_victory.nil?
  end

  def select_winner(winning_team, cups_left)
    if winning_team == 1
      self.is_team_one_victory = true
    elsif winning_team == 2
      self.is_team_one_victory = false
    else
      raise "winning team must be 1 or 2"
    end

    self.cups_left = cups_left

    save!
  end

  private

  def not_same_player
    if [self.player_one_id, self.player_two_id, self.player_three_id, self.player_four_id].uniq.size != 4
      self.errors.add(:base, "Can't add the same player fool!")
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_filter :authenticate
  layout 'admin'

  # GET /admin/games
  # GET /admin/games.json
  def index
    @games = Game.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /admin/games/1
  # GET /admin/games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /admin/games/new
  # GET /admin/games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /admin/games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /admin/games
  # POST /admin/games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to admin_games_url, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/games/1
  # PUT /admin/games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to admin_games_url, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/games/1
  # DELETE /admin/games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to admin_games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :set_league

  # GET /games
  # GET /games.json
  def index
    @games = @league.games.reorder("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = @league.games.build
    @game.build_default_assocations
    @players = Player.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
    @players = Player.all
  end

  # POST /games
  # POST /games.json
  def create
    @game = @league.games.build(params[:game])
    use_interactive_mode = params[:mode] == "interactive"
    @game.is_team_one_victory = true unless use_interactive_mode

    respond_to do |format|
      if @game.save
        format.html do
          if use_interactive_mode
            redirect_to shot_tracker_league_game_url(@league, @game), notice: 'Game was successfully created.'
          else
            redirect_to @league, notice: 'Game was successfully created.'
          end
        end
        format.json { render json: @game, status: :created, location: @game }
      else
        @players = Player.all
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_winner
    @game = Game.find(params[:id])
    cups_left = params[:cups_left].to_i
    winning_team = params[:winning_team].to_i

    @game.select_winner(winning_team, cups_left)

    redirect_to @league, notice: 'Game was successfully recorded!'
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to league_game_path(@league, @game), notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to league_games_url }
      format.json { head :no_content }
    end
  end

  def odds
    @game = @league.games.build(params[:game])
    @players = Player.all

    respond_to do |format|
      @game.build_default_assocations unless @expected_outcome = @game.expected_outcome
      format.html {  }
    end
  end

  def shot_tracker
    @game = Game.find(params[:id])
    raise "Cannot use shot_tracker on completed game" unless @game.is_pending?
  end

  # POST /games/1/shots
  def shots_index
    @shots = Shot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shots }
    end
  end

  def create_shot
    @game = Game.find(params[:id])
    @shot = @game.shots.build(params[:shot])

    respond_to do |format|
      format.json do
        if @shot.save
          render json: @shot.to_json(:methods => [:player_name, :team])
        else
          render json: @shot.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def set_league
    @league = League.find(params[:league_id])
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for([@league, @game]) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_one_id, "Team One" %><br />
    <%= f.select :player_one_id,  player_names %>
  </div>
  <div class="field">
    <%= f.label :player_two_id, "Team One" %><br />
    <%= f.select :player_two_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :player_three_id, "Team Two" %><br />
    <%= f.select :player_three_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :player_four_id, "Team Two" %><br />
    <%= f.select :player_four_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :cups_left %><br />
    <%= f.number_field :cups_left %>
  </div>
  <div class="actions">
    <%= hidden_field_tag :mode %>
    <%= f.submit "Team One Wins", name: "completed" %>
    <%= f.submit "Start Interactive Mode", name: "interactive" %>
  </div>
<% end %>

<% content_for(:script) do %>
<script>
$('input[type=submit]').click(function(){
$('#mode').val($(this).attr('name'));
$(this).submit();
});
</script>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', league_game_path(@league, @game) %> |
<%= link_to 'Back', league_games_path(@league) %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>League</th>
    <th>Player one</th>
    <th>Player two</th>
    <th>Player three</th>
    <th>Player four</th>
    <th>Winning team</th>
    <th>Cups left</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= @league.name %></td>
    <td><%= game.player_one.name %></td>
    <td><%= game.player_two.name %></td>
    <td><%= game.player_three.name %></td>
    <td><%= game.player_four.name %></td>
    <td><%= winner_string(game) %></td>
    <td><%= game.cups_left %></td>
    <td><%= game.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
    <td><%= link_to 'Edit', edit_league_game_path(@league, game) %></td>
    <td><%= link_to('Interactive Mode', shot_tracker_league_game_path(@league, game)) if game.is_pending? %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Game', new_league_game_path %><br />
<%= link_to "Back to league page", league_path(@league) %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', league_games_path %>

app/views/games/odds.html.erb
<h1>Odds Calculator</h1>

<% if @expected_outcome %>
EXPECTED OUTCOME: <br />
Team 1 has a total score of <%= @game.total_winner_score %>, and a <%= number_to_percentage(@expected_outcome.first * 100) %> chance to win<br />
Team 2 has a total score of <%= @game.total_loser_score %>, and a <%= number_to_percentage(@expected_outcome.last * 100) %> chance to win

<hr />
<% end %>

<%= form_for @game, :url => odds_league_games_path(@league, @game), :method => :get do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_one, "Team 1 Player 1" %><br />
    <%= f.select :player_one_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :player_two, "Team 1 Player 2" %><br />
    <%= f.select :player_two_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :player_three, "Team 2 Player 1" %><br />
    <%= f.select :player_three_id, player_names %>
  </div>
  <div class="field">
    <%= f.label :player_four, "Team 2 Player 2" %><br />
    <%= f.select :player_four_id, player_names %>
  </div>
  <div class="actions">
    <%= f.submit "Calculate Odds" %>
  </div>
<% end %>



<%= link_to "Back to league page", league_path(@game.league_id), :id => 'back-to-league' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Team 1</h2>
<p>
  <b>Player one:</b>
  <%= @game.player_one.name %>
</p>

<p>
  <b>Player two:</b>
  <%= @game.player_two.name %>
</p>

<h2>Team 2</h2>
<p>
  <b>Player one:</b>
  <%= @game.player_three.name %>
</p>

<p>
  <b>Player two:</b>
  <%= @game.player_four.name %>
</p>

<h2>Winning Team <%= @game.is_team_one_victory ? "TEAM 1" : "TEAM 2" %></h2>
<p>
  <b>Cups left:</b>
  <%= @game.cups_left %>
</p>


<%= link_to 'Edit', edit_league_game_path(@league, @game) %> |
<%= link_to 'Back', league_games_path %>